"""new-mig3

Revision ID: 20715aee2004
Revises: 2693e714cfb4
Create Date: 2026-02-14 20:08:26.118030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20715aee2004'
down_revision: Union[str, Sequence[str], None] = '2693e714cfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('username', sa.String(), nullable=False))
    op.add_column('UserProfile', sa.Column('password', sa.String(), nullable=False))
    op.add_column('UserProfile', sa.Column('access_tocken', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'access_tocken')
    op.drop_column('UserProfile', 'password')
    op.drop_column('UserProfile', 'username')
    # ### end Alembic commands ###
