"""new-mig3

Revision ID: 2693e714cfb4
Revises: 03e64e268b2f
Create Date: 2026-02-14 20:08:16.234602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2693e714cfb4'
down_revision: Union[str, Sequence[str], None] = '03e64e268b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'password')
    op.drop_column('UserProfile', 'username')
    op.drop_column('UserProfile', 'access_tocken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('access_tocken', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('UserProfile', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('UserProfile', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
